#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
python3 -m pip install pytest pytest-asyncio pytest-homeassistant-custom-component aioresponses
